
SELECT * FROM IPOS_PERFIL;
SELECT * FROM IPOS_USUARIO;
SELECT * FROM IPOS_FUNCION;
SELECT * FROM IPOS_UNIDAD_MEDIDA;
SELECT * FROM IPOS_INSUMO;
--  PERFIL CON FUNCIONES
SELECT P.*, F.* FROM IPOS_PERF_FUNC PF, IPOS_PERFIL P, IPOS_FUNCION F
WHERE
PF.FUNCION_ID = F.FUNCION_ID
AND PF.PERFIL_ID = P.PERFIL_ID
ORDER BY PF.PERFIL_ID
;
--  USUARIO CON PERFIL
SELECT U.*, P.NOMBRE PERFIL FROM IPOS_USUARIO U, IPOS_PERFIL P WHERE U.PERFIL_ID = P.PERFIL_ID
;
--  INSUMOS CON UNIDAD DE MEDIDA
SELECT * FROM IPOS_INSUMO_VIEW
;
--  CONSUMO DE INSUMOS CON UNIDAD DE MEDIDA
SELECT * FROM IPOS_INSUMO_CONSUMO_VIEW
;
--  RECETAS CON INGREDIENTES 
SELECT * FROM IPOS_RECETA_VIEW;

-- PEDIDOS CON RECETAS
SELECT * FROM IPOS_PEDIDO_VIEW
;