CREATE TABLE IPOS_PERFIL(
PERFIL_ID NUMBER PRIMARY KEY NOT NULL,
NOMBRE VARCHAR2(30) NOT NULL
);

CREATE TABLE IPOS_USUARIO(
USUARIO_ID NUMBER  PRIMARY KEY NOT NULL,
NOMBRE VARCHAR2(30) NOT NULL,
PASS_USU VARCHAR2(20),
PERFIL_ID NUMBER NOT NULL,
FOREIGN KEY (PERFIL_ID) REFERENCES IPOS_PERFIL(PERFIL_ID)
);

CREATE TABLE IPOS_FUNCION(
FUNCION_ID NUMBER PRIMARY KEY NOT NULL,
NOMBRE VARCHAR2(30) NOT NULL
);

CREATE TABLE IPOS_PERF_FUNC(
PERFIL_ID NUMBER NOT NULL,
FUNCION_ID NUMBER NOT NULL,
PRIMARY KEY (PERFIL_ID,FUNCION_ID),
FOREIGN KEY (PERFIL_ID) REFERENCES IPOS_PERFIL(PERFIL_ID),
FOREIGN KEY (FUNCION_ID) REFERENCES IPOS_FUNCION(FUNCION_ID)
);
CREATE TABLE IPOS_UNIDAD_MEDIDA(
UNIDAD_MEDIDA_ID NUMBER NOT NULL PRIMARY KEY,
COD_UNIDAD_MEDIDA VARCHAR2(10) NOT NULL,
NOMBRE VARCHAR2(30) NOT NULL,
SIMBOLO VARCHAR2(30) NOT NULL,
PERMITE_DECIMALES NUMBER NOT NULL
);
CREATE TABLE IPOS_INSUMO(
INSUMO_ID NUMBER NOT NULL PRIMARY KEY,
NOMBRE VARCHAR2(50) NOT NULL,
CANTIDAD NUMBER NOT NULL,
DESCRIPCION VARCHAR2(100),
NIVEL_MINIMO NUMBER NOT NULL,
NIVEL_OPTIMO NUMBER NOT NULL,
UNIDAD_MEDIDA_ID NUMBER NOT NULL,
FOREIGN KEY (UNIDAD_MEDIDA_ID) REFERENCES IPOS_UNIDAD_MEDIDA(UNIDAD_MEDIDA_ID)
);
CREATE TABLE IPOS_INSUMO_CONSUMO(
INSUMO_CONSUMO_ID NUMBER NOT NULL PRIMARY KEY,
CANTIDAD_CONSUMIDA NUMBER NOT NULL,
FECHA_CONSUMO DATE NOT NULL,
INSUMO_ID NUMBER NOT NULL,
FOREIGN KEY (INSUMO_ID) REFERENCES IPOS_INSUMO(INSUMO_ID)
);
CREATE TABLE IPOS_RECETA(
RECETA_ID NUMBER NOT NULL PRIMARY KEY,
NOMBRE_RECETA VARCHAR2(100),
DESCRIPCION_RECETA VARCHAR2(200)
);
CREATE TABLE IPOS_INGREDIENTE(
INGREDIENTE_ID NUMBER NOT NULL PRIMARY KEY,
CANTIDAD_INGREDIENTE NUMBER NOT NULL,
INSUMO_ID NUMBER NOT NULL,
RECETA_ID NUMBER NOT NULL,
FOREIGN KEY (INSUMO_ID) REFERENCES IPOS_INSUMO(INSUMO_ID),
FOREIGN KEY (RECETA_ID) REFERENCES IPOS_RECETA(RECETA_ID)
);
CREATE TABLE IPOS_PEDIDO(
PEDIDO_ID NUMBER NOT NULL PRIMARY KEY,
FECHA_PEDIDO DATE NOT NULL
);
CREATE TABLE IPOS_DETALLE_PEDIDO(
DETALLE_PEDIDO_ID NUMBER NOT NULL PRIMARY KEY,
CANTIDAD_DETALLE NUMBER NOT NULL,
PEDIDO_ID NUMBER NOT NULL,
RECETA_ID NUMBER NOT NULL,
FOREIGN KEY (PEDIDO_ID) REFERENCES IPOS_PEDIDO(PEDIDO_ID),
FOREIGN KEY (RECETA_ID) REFERENCES IPOS_RECETA(RECETA_ID)
);
/*
  SECUENCIAS
*/ 
CREATE SEQUENCE SEQ_IPOS_DETALLE_PEDIDO;
CREATE SEQUENCE SEQ_IPOS_PEDIDO;
CREATE SEQUENCE SEQ_IPOS_PERFIL;
CREATE SEQUENCE SEQ_IPOS_FUNCION;
CREATE SEQUENCE SEQ_IPOS_USUARIO;
CREATE SEQUENCE SEQ_IPOS_UNIDAD_MEDIDA;
CREATE SEQUENCE SEQ_IPOS_INSUMO;
CREATE SEQUENCE SEQ_IPOS_RECETA;
CREATE SEQUENCE SEQ_IPOS_INGREDIENTE;
CREATE SEQUENCE SEQ_IPOS_INSUMO_CONSUMO;
COMMIT;