CREATE TABLE IPOS_PERFIL(
PERFIL_ID NUMBER PRIMARY KEY NOT NULL,
NOMBRE VARCHAR2(30) NOT NULL
);

CREATE TABLE IPOS_USUARIO(
USUARIO_ID NUMBER  PRIMARY KEY NOT NULL,
NOMBRE VARCHAR2(30) NOT NULL,
PASS_USU VARCHAR2(20),
PERFIL_ID NUMBER NOT NULL,
FOREIGN KEY (PERFIL_ID) REFERENCES IPOS_PERFIL(PERFIL_ID)
);

CREATE TABLE IPOS_FUNCION(
FUNCION_ID NUMBER PRIMARY KEY NOT NULL,
NOMBRE VARCHAR2(30) NOT NULL
);

CREATE TABLE IPOS_PERF_FUNC(
PERFIL_ID NUMBER NOT NULL,
FUNCION_ID NUMBER NOT NULL,
PRIMARY KEY (PERFIL_ID,FUNCION_ID),
FOREIGN KEY (PERFIL_ID) REFERENCES IPOS_PERFIL(PERFIL_ID),
FOREIGN KEY (FUNCION_ID) REFERENCES IPOS_FUNCION(FUNCION_ID)
);

/*
  SECUENCIAS
*/ 
CREATE SEQUENCE SEQ_IPOS_PERFIL;
CREATE SEQUENCE SEQ_IPOS_FUNCION;
CREATE SEQUENCE SEQ_IPOS_USUARIO;