INSERT INTO IPOS_PERFIL (PERFIL_ID,NOMBRE) VALUES(SEQ_IPOS_PERFIL.NEXTVAL,'ADMINISTRADOR');
INSERT INTO IPOS_PERFIL (PERFIL_ID,NOMBRE) VALUES(SEQ_IPOS_PERFIL.NEXTVAL,'CAJERO');
INSERT INTO IPOS_PERFIL (PERFIL_ID,NOMBRE) VALUES(SEQ_IPOS_PERFIL.NEXTVAL,'DESPACHADOR');
INSERT INTO IPOS_PERFIL (PERFIL_ID,NOMBRE) VALUES(SEQ_IPOS_PERFIL.NEXTVAL,'JEFE_ALMACEN');

INSERT INTO IPOS_FUNCION (FUNCION_ID,NOMBRE) VALUES(SEQ_IPOS_FUNCION.NEXTVAL,'INSUMO_REGISTRAR');
INSERT INTO IPOS_FUNCION (FUNCION_ID,NOMBRE) VALUES(SEQ_IPOS_FUNCION.NEXTVAL,'INSUMO_RECARGAR');
INSERT INTO IPOS_FUNCION (FUNCION_ID,NOMBRE) VALUES(SEQ_IPOS_FUNCION.NEXTVAL,'INSUMO_CONSULTAR');
INSERT INTO IPOS_FUNCION (FUNCION_ID,NOMBRE) VALUES(SEQ_IPOS_FUNCION.NEXTVAL,'INSUMO_CONSUMOS');
INSERT INTO IPOS_FUNCION (FUNCION_ID,NOMBRE) VALUES(SEQ_IPOS_FUNCION.NEXTVAL,'INSUMO_LIMITES');
INSERT INTO IPOS_FUNCION (FUNCION_ID,NOMBRE) VALUES(SEQ_IPOS_FUNCION.NEXTVAL,'ALERTA_INVENTARIO');
INSERT INTO IPOS_FUNCION (FUNCION_ID,NOMBRE) VALUES(SEQ_IPOS_FUNCION.NEXTVAL,'RECETAS_CREACION');
INSERT INTO IPOS_FUNCION (FUNCION_ID,NOMBRE) VALUES(SEQ_IPOS_FUNCION.NEXTVAL,'RECETAS_CONSULTAS');
INSERT INTO IPOS_FUNCION (FUNCION_ID,NOMBRE) VALUES(SEQ_IPOS_FUNCION.NEXTVAL,'RECETAS_CONSUMOS');
INSERT INTO IPOS_FUNCION (FUNCION_ID,NOMBRE) VALUES(SEQ_IPOS_FUNCION.NEXTVAL,'PEDIDOS_REGISTRO');
INSERT INTO IPOS_FUNCION (FUNCION_ID,NOMBRE) VALUES(SEQ_IPOS_FUNCION.NEXTVAL,'PEDIDOS_CONSULTA_COLA');
INSERT INTO IPOS_FUNCION (FUNCION_ID,NOMBRE) VALUES(SEQ_IPOS_FUNCION.NEXTVAL,'PEDIDOS_CONSULTAR');

INSERT INTO IPOS_USUARIO (USUARIO_ID,NOMBRE,PASS_USU,PERFIL_ID) VALUES (SEQ_IPOS_USUARIO.NEXTVAL,'ADMIN','1234',(SELECT PERFIL_ID FROM IPOS_PERFIL WHERE NOMBRE = 'ADMINISTRADOR'));
INSERT INTO IPOS_USUARIO (USUARIO_ID,NOMBRE,PASS_USU,PERFIL_ID) VALUES (SEQ_IPOS_USUARIO.NEXTVAL,'CAJERO','1234',(SELECT PERFIL_ID FROM IPOS_PERFIL WHERE NOMBRE = 'CAJERO'));
INSERT INTO IPOS_USUARIO (USUARIO_ID,NOMBRE,PASS_USU,PERFIL_ID) VALUES (SEQ_IPOS_USUARIO.NEXTVAL,'DESPACHADOR','1234',(SELECT PERFIL_ID FROM IPOS_PERFIL WHERE NOMBRE = 'DESPACHADOR'));
INSERT INTO IPOS_USUARIO (USUARIO_ID,NOMBRE,PASS_USU,PERFIL_ID) VALUES (SEQ_IPOS_USUARIO.NEXTVAL,'JEFE_ALMACEN','1234',(SELECT PERFIL_ID FROM IPOS_PERFIL WHERE NOMBRE = 'JEFE_ALMACEN'));