DECLARE
PERFIL_ID_AUX NUMBER;
CURSOR CURSOR_INSUMOS IS SELECT * FROM IPOS_FUNCION WHERE NOMBRE LIKE '%INSUMO%' OR NOMBRE LIKE '%INVENTARIO%';
BEGIN
  SELECT PERFIL_ID INTO PERFIL_ID_AUX FROM IPOS_PERFIL WHERE NOMBRE = 'JEFE_ALMACEN';
  FOR REGISTRO IN CURSOR_INSUMOS LOOP
    INSERT INTO IPOS_PERF_FUNC (PERFIL_ID,FUNCION_ID) VALUES (PERFIL_ID_AUX,REGISTRO.FUNCION_ID);
  END LOOP;
END;