-- VISTA INSUMO
CREATE OR REPLACE VIEW IPOS_INSUMO_VIEW AS
SELECT 
I.*,
UM.NOMBRE NOMBRE_UM,
UM.PERMITE_DECIMALES,
UM.SIMBOLO,
UM.COD_UNIDAD_MEDIDA 
FROM IPOS_INSUMO I, IPOS_UNIDAD_MEDIDA UM
WHERE I.UNIDAD_MEDIDA_ID = UM.UNIDAD_MEDIDA_ID
;
--  VISTA CONSUMO DE INSUMOS
CREATE OR REPLACE VIEW IPOS_INSUMO_CONSUMO_VIEW
AS
SELECT IC.*,
I.NOMBRE INSUMO_NOM,
UM.UNIDAD_MEDIDA_ID,
UM.SIMBOLO,
UM.NOMBRE UNIDAD_MEDIDA
FROM IPOS_INSUMO_CONSUMO IC, IPOS_INSUMO I, IPOS_UNIDAD_MEDIDA UM
WHERE 
IC.INSUMO_ID = I.INSUMO_ID
AND UM.UNIDAD_MEDIDA_ID = I.UNIDAD_MEDIDA_ID
;
--  RECETA CON INGREDIENTES
CREATE OR REPLACE VIEW IPOS_RECETA_VIEW
AS
SELECT 
R.*,
ING.INGREDIENTE_ID,
ING.CANTIDAD_INGREDIENTE,
IVIEW.INSUMO_ID,
IVIEW.NOMBRE NOMBRE_INGREDIENTE,
IVIEW.UNIDAD_MEDIDA_ID,
IVIEW.NOMBRE_UM
FROM IPOS_RECETA R, IPOS_INGREDIENTE ING, IPOS_INSUMO_VIEW IVIEW
WHERE R.RECETA_ID = ING.RECETA_ID
AND IVIEW.INSUMO_ID = ING.INSUMO_ID
;
--  PEDIDO CON SUS RECETAS
CREATE OR REPLACE VIEW IPOS_PEDIDO_VIEW
AS
SELECT 
P.* ,
DP.DETALLE_PEDIDO_ID, DP.CANTIDAD_DETALLE,
R.*
FROM IPOS_PEDIDO P, IPOS_DETALLE_PEDIDO DP, IPOS_RECETA R
WHERE 
P.PEDIDO_ID = DP.PEDIDO_ID
AND R.RECETA_ID = DP.RECETA_ID
;

COMMIT;